services:
  langgraph-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rocket-server
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
      - "8123:8123"  # Map container port 8123 to host port 8123 (direct LangGraph)
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      # Override any specific environment variables if needed
      - PYTHONPATH=/deps/deploy-langgraph-server-auth
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ok"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - langgraph-network

networks:
  langgraph-network:
    driver: bridge
